### ISSUE TITLE
Fernsteuerung Ansteuerung--> Motorsteuerung Max Geschwindigkeit, delay bei Tastendruck, z.B. rechter Pfeil = rechtskurve so lange du hälst etc....

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/Mohne#1]

**Comment by LudiP** [comment]
http://www.instructables.com/id/Controlling-a-Raspberry-Pi-RC-Car-With-a-Keyboard/

**Comment by MaxMoebes** [comment]
Link für den Download von Getchar für die Fernsteuerung:
https://custom-build-robots.com/raspberry-pi-roboter-download

**Comment by gchrizZz** [comment]
https://stackoverflow.com/questions/45584937/how-to-detect-key-release-with-python-not-keypress?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
