### ISSUE TITLE
Bilder automatisch uploaden programmieren (optional)

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/Mohne#10]

**Comment by MaxMoebes** [comment]
Vorschlag: Bilder pushen über Twitter

https://ttrzpit.wordpress.com/2015/07/21/tweeting-pictures-from-the-raspberry-pi-camera-with-python/

**Comment by MaxMoebes** [comment]
Twitter Account: Mohne_2.0
https://twitter.com/0Mohne

API ist fertig und kann über den Account aufgerufen werden.

**Comment by MaxMoebes** [comment]
Die Mohne kann jetzt Twittern!! Bilder werden sofort zu twitter hochgeladen und sind so auch später leicht zugänglich. Hier und da kann noch was verbessert werden, generell aber fertig!

**Comment by LudiP** [comment]
https://projects.raspberrypi.org/en/projects/magic-8-ball/6

Gute Erklärung um Random Statustexte zu verwenden. 
Alternativ können wir auch einen Zähler einbauen der die Anzahl der hochgeladenen Fotos zählt und im Status dann zB sowas steht: 1. Hindernis:  2. Hindernis:  etc...
Bevorzugen würd ich witzige und zufällige Texte :P

**Comment by MaxMoebes** [comment]
Hab die random Statustexte in den TwitterPush Code eingebaut. Müssen uns jetzt nur noch was gutes überlegen für die Statusmeldungen.
