### ISSUE TITLE
Klärungsmail an Hr. Lettnin/ Schmiedinger bzgl. Aufgabenstellung Matlab - BilderUpload + Kein Tutorial...

### ISSUE THREAD

**Issue by gchrizZz** [gchrizZz/Mohne#16]

**Comment by ChristophJungwirth** [comment]
Hallo Herr Lettnin, 

wir sitzen gerade bei der Aufgabenteilung in unserem Projekt und sind uns bei folgenden Punkten nicht sicher was damit gemeint ist. 

1.	Wie soll Matlab in Bezug auf die Telemetrie-Daten angewendet werden (Wenn überhaupt)?
Sollen wir hier eine Live-Verbindung während der Fahrt darstellen auf einem lokalen Laptop oder über Matlab online? Macht es hier nicht mehr Sinn, mehrere Konten des ThingsSpeak miteinander zu verknüpfen und mit Hilfe von mqtt-Protokoll zu Verknüpfen. 
2.	Bei der Hinderniserkennung soll ein Bild vom Hindernis gemacht werden, wo bzw. wie soll dieses den gespeichert werden?
3.	Wie soll die Simulation aussehen? Haben wir hier noch eine Vorlesung?
4.     Muss unbedingt ein eigener Channel bei ThingsSpeak pro Sensor erstellt werden und wenn ja Warum?

Über eine schnelle Rückmeldung würden wir uns freuen. 

Mit freundlichen Grüßen

Christoph Jungwirth

**Comment by ChristophJungwirth** [comment]
zu Punkt 1:
ist egal welches System. Auch können mehrere Sensoren auf einem Channel laufen. 
zu Punkt 2:
Bild machen ja; Speicherort ist egal. 
zu Punkt 3:
Wird noch am 21.4.2018 bekannt gegeben.
zu Punkt 4:
Nein!
